= Troubleshooting
:toc:

== Bread Issues

=== The Bread Has Not Risen

If the bread has not risen, first check that you used fresh yeast.

You can also add more yeast to the dough and knead it again.

Put the dough somewhere warm and leave it for another 10 minutes.

If this doesn't work, put the dough in the freezer for 20 minutes and then try again.

=== The Bread Is Too Hard

If the bread is too hard, bake it for longer next time.

You can also increase the oven temperature so that the outside cooks more quickly.

Make sure you use plenty of flour when kneading.

=== The Bread Is Burnt

If the bread is burnt on top but still raw inside, increase the oven temperature and bake it for another 10 minutes.

== Apple Tart Issues

=== The Pastry Is Too Wet

If the pastry is too wet, add more water and continue kneading.

If this does not work, add more flour.

=== The Pastry Has Not Risen

Make sure you leave the pastry somewhere warm.

If it does not rise, add another packet of yeast and leave it for another hour.

=== The Apples Are Too Hard

If the apples are still hard after baking, increase the oven temperature to 220°C and bake for another 20 minutes.

Check the tart regularly so that it does not burn.
